name: ace_thetic
description: An Ecommerce application for an auction.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.6
  provider: ^6.0.5
  file_picker: ^5.5.0
  flutter_secure_storage: ^9.0.0
  uuid: ^3.0.7
  intl: ^0.18.1
  mime: ^1.0.4
  http_parser: ^4.0.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/dashboard_bg.jpg
